name: hava_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  vexana: ^5.0.0
  json_annotation: ^4.9.0
  geolocator: ^13.0.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
